[package]
name = "iroh-minecraft"
version = "0.1.0"
edition = "2021"

[dependencies]
iroh-net = "0.27.0"
iroh-base = "0.27.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
base64 = "0.21"
futures = "0.3"
